language: scala
matrix:
  include:
    - scala: 2.11.7
      jdk: oraclejdk7
    - scala: 2.11.7
      jdk: oraclejdk8
    - scala: 2.12.1
      jdk: oraclejdk8
before_script:
  - sudo chmod +x /usr/local/bin/sbt
script:
  - sbt -no-colors ++$TRAVIS_SCALA_VERSION test
